# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.1.4
          ports:
          - containerPort: 5050
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.out-of-scope.global:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.out-of-scope.global:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.in-scope.svc.cluster.local:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.out-of-scope.global:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.out-of-scope.global:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.out-of-scope.global:7070"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: {{ required "frontend_image is required" .Values.frontend_image}}
          ports:
          - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 80
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
              - name: "X-Forwarded-Proto"
                value: "https"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 80
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
              - name: "X-Forwarded-Proto"
                value: "https"
          env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.out-of-scope.global:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.out-of-scope.global:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.out-of-scope.global:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice.out-of-scope.global:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.out-of-scope.global:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice.in-scope.svc.cluster.local:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice.out-of-scope.global:9555"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.1.4
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
